apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudstate-operator-config
data:
  config: |
    cloudstate.operator {
      # Watch configuration
      watch {

        # This should be a list of namespaces to watch. Either should contain a single "*" to watch all namespaces
        # (this is configured in more detail below), or should be a list of namespaces.
        namespaces = ["*"]
      }

      # Proxy configuration
      proxy {
        image {
          cassandra = "cloudstateio/cloudstate-proxy-native-cassandra:latest"
          postgres =  "cloudstateio/cloudstate-proxy-postgres:latest"
          no-store = "cloudstateio/cloudstate-proxy-native-no-store:latest"
          in-memory = "cloudstateio/cloudstate-proxy-native-in-memory:latest"
        }
      }
    }

